/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nafkhanzam.checkmatefinder;

import com.github.bhlangonijr.chesslib.Board;

import org.junit.Before;
import org.junit.Test;

public class AppTest {

    private Board board;

    @Before
    public void init() {
        board = new Board();
    }

    @Test
    public void testPuzzle1() {

    }
}
